name: mangohud
on:
  push:
    branches: [main, sm8250]
    paths: ['mangohud/**', 'oci/**', '.github/workflows/mangohud.yml', '.github/workflows/_package-image.yml', 'toolchain.env']
  workflow_dispatch:
permissions:
  contents: read
  packages: write
  id-token: write
jobs:
  build:
    uses: ./.github/workflows/_package-image.yml
    secrets: inherit
    with:
      package: mangohud
